NLP - Stemming Directive
data-integrations/wrangler pull request #35
Opened 2017-02-08 18:48 UTC by nitinmotgi

2017-02-08 19:39 UTC, sreevatsanraman requested changes
Minor comments, fix and merge.

2017-02-08 19:39 UTC, sreevatsanraman commented on docs/directives/stemming.md
> +# Write as JSON Map
This should be NLP stemming?

2017-02-08 19:39 UTC, sreevatsanraman commented on wrangler-core/src/main/java/co/cask/wrangler/steps/nlp/Stemming.java
> +import edu.emory.mathcs.backport.java.util.Arrays;
Should this be java.util.Arrays instead?

2017-02-08 19:39 UTC, sreevatsanraman commented on wrangler-core/src/main/java/co/cask/wrangler/steps/nlp/internal/PorterStemmer.java
> +/*
Add license from the code that is copied from Stanford NLP.

2017-02-08 19:39 UTC, sreevatsanraman commented on wrangler-core/src/test/java/co/cask/wrangler/steps/nlp/StemmingTest.java
> +}
new line.

2017-02-12 02:58 UTC, nitinmotgi commented on wrangler-core/src/main/java/co/cask/wrangler/steps/nlp/Stemming.java
> +import edu.emory.mathcs.backport.java.util.Arrays;
fixed

2017-02-12 03:03 UTC, nitinmotgi commented on wrangler-core/src/main/java/co/cask/wrangler/steps/nlp/internal/PorterStemmer.java
> +/*
fixed

2017-02-12 03:03 UTC, nitinmotgi commented on wrangler-core/src/test/java/co/cask/wrangler/steps/nlp/StemmingTest.java
> +}
done

2017-02-12 03:14 UTC, merged