Fix json generation script
data-integrations/wrangler pull request #45
Opened 2017-02-28 01:17 UTC by rohitsinha54

same as https://github.com/hydrator/naive-bayes-analytics/pull/5

2017-02-28 08:07 UTC, nitinmotgi requested changes

2017-02-28 08:07 UTC, nitinmotgi commented on pom.xml
> +    <app.parents>system:cdap-etl-batch[4.1.0,4.2.0-SNAPSHOT),system:cdap-etl-realtime[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-pipeline[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-streams[4.1.0,4.2.0-SNAPSH
Why do we need batch and realtime when we have data pipeline and streams ?

2017-02-28 20:14 UTC, rohitsinha54 commented on pom.xml
> +    <app.parents>system:cdap-etl-batch[4.1.0,4.2.0-SNAPSHOT),system:cdap-etl-realtime[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-pipeline[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-streams[4.1.0,4.2.0-SNAPSH
Not entirely sure. It depend on it in older script version:
https://github.com/hydrator/wrangler/pull/45/files#diff-600376dffeb79835ede4a0b285078036L234

@albertshau Might be able to clarify if its needed or not.

2017-02-28 20:15 UTC, albertshau commented on pom.xml
> +    <app.parents>system:cdap-etl-batch[4.1.0,4.2.0-SNAPSHOT),system:cdap-etl-realtime[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-pipeline[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-streams[4.1.0,4.2.0-SNAPSH
its still needed if we want it to be available with those deprecated apps. Whether it should be there I guess is a product decision?

2017-03-01 05:12 UTC, bdmogal commented on pom.xml
> +    <app.parents>system:cdap-etl-batch[4.1.0,4.2.0-SNAPSHOT),system:cdap-etl-realtime[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-pipeline[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-streams[4.1.0,4.2.0-SNAPSH
Unless somethimg breaks (I know there was some plugin function that required this) without this, lets not add it

2017-03-01 06:50 UTC, merged