Directive validation
data-integrations/wrangler pull request #653
Opened 2023-07-25 11:08 UTC by shrverma

2023-07-25 11:49 UTC, vanathi-g requested changes

2023-07-25 11:49 UTC, vanathi-g commented on wrangler-api/src/main/java/io/cdap/wrangler/api/DirectiveRelationalTransform.java
> + *  Copyright © 2017-2019 Cask Data, Inc.
nit: fix license file

2023-07-25 11:49 UTC, vanathi-g commented on wrangler-transform/src/main/java/io/cdap/wrangler/Wrangler.java
> +      throw new RuntimeException(e);
Add more descriptive messages to all the errors if re-throwing or alternatively just add to failure collector. Can also merge the catch blocks if the errors are handled the same way: Ex: catch (DirectiveParseException | RecipeException e)

2023-07-25 11:49 UTC, vanathi-g commented on wrangler-transform/src/main/java/io/cdap/wrangler/Wrangler.java
> +import io.cdap.wrangler.api.DirectiveRelationalTransform;
nit: remove unused imports

2023-07-25 11:49 UTC, vanathi-g commented on wrangler-transform/src/main/java/io/cdap/wrangler/Wrangler.java
>    private void validateSQLModeDirectives(FailureCollector collector) {
Can change the function to take a list of directives and check whether they are sql supported. It seems like the function performs too many different operations

2023-07-25 11:49 UTC, vanathi-g commented on wrangler-transform/src/main/java/io/cdap/wrangler/Wrangler.java
> +    registry = SystemDirectiveRegistry.INSTANCE;
Also, this logic of loading directives is repeated in multiple places in this file. Make it a separate function?

2023-07-26 12:20 UTC, vanathi-g approved these changes

2023-07-31 14:49 UTC, saimukkamala approved these changes

2023-07-31 15:02 UTC, merged